import { Article } from './models/article.model'

export const ARTICLES: Article[] = [
  new Article('Justice Dept. Rank-and-File Tell of Discontent Over Sessions’s Approach', 'Attorney General Jeff Sessions was so determined to carry out his agenda that he ignored dissent, at times putting the Trump administration on track to lose in court, according to interviews.', 'Now, discontent and infighting have taken hold at the Justice Department.', '', 'https://static01.nyt.com/images/2018/09/04/us/politics/00dc-justice1/00dc-justice1-threeByTwoSmallAt2X.jpg?quality=75&auto=webp&disable=upscale', 'Justice Department lawyers have raised concerns about Attorney General Jeff Sessions pursuing legally indefensible cases and a lack of support when they tried to warn him.','Doug Mills/The New York Times','','2h ago',  'TRUMP ADMINISTRATION'),
  new Article('At a Montana rally, President Trump praised a lawmaker who body-slammed a reporter last year: “That’s my kind of guy.”', '“It’s something else — it’s feeling, emotion, preference, loyalty, convenience of the moment,” said Michael V. Hayden, a former C.I.A. director.', '', '', '', '','','','Oct. 18',  'TRUMP ADMINISTRATION'),
  new Article('A President Who Believes He Is Entitled to His Own Facts', '', '', '', '', '','','','Oct. 18',  'TRUMP ADMINISTRATION'),
  new Article('In 2020, Democrats Expect a Female Front-Runner. Or Three.', 'Three prominent female Democrats all but openly began running for president this week.', 'A choice of female candidates could potentially divide voters determined to nominate a woman and perhaps heighten scrutiny of how male candidates have treated women in public and private life.', '', 'https://static01.nyt.com/images/2018/10/14/us/politics/14women1/merlin_145176279_fae93095-0159-4530-ad71-2a104ef83f26-threeByTwoLargeAt2X.jpg?quality=75&auto=webp&disable=upscale&width=1620', 'Senator Elizabeth Warren of Massachusetts campaigned with Stacey Abrams, the Democratic nominee for governor, in Morrow, Ga., last week.','Melissa Golden for The New York Times','','2h ago',  'ELECTION 2018'),
    new Article('For a Change, Democrats Seem Set to Equal or Exceed Republicans in Turnout', 'Polls show enthusiasm surging in many mostly white suburban districts, but less so among young and nonwhite voters.', '', '', '', '','','','10h ago',  'ELECTION 2018'),
    new Article('The midterms have been Trumpified: candidates are imitating the president’s raw and combative style online.', '', '', '', '', '','','','10h ago',  'ELECTION 2018'),
]
